---
- name: "Manage Talos VMs on Proxmox"
  no_log: true
  module_defaults:
    community.proxmox.proxmox_kvm:
      api_host: "{{ proxmox_host }}"
      api_user: "{{ proxmox_user }}"
      api_token_id: "{{ proxmox_token_id | default(omit) }}"
      api_token_secret: "{{ proxmox_token_secret | default(omit) }}"
      api_password: "{{ proxmox_password | default(omit) }}"
      node: "{{ proxmox_node }}"
  block:
  - name: "Create {{ talos_cp_count }} Talos Control Plane VM(s)"
    community.proxmox.proxmox_kvm:
      name: "talos-cp-{{ item + 1 }}"
      cores: "{{ talos_cp_cores }}"
      cpu: host
      memory: "{{ talos_cp_memory }}"
      ipconfig:
        ipconfig0: "ip={{ network }}.{{ start_octet + item }}/{{ cidr }},gw={{ gateway }}"
      virtio:
        virtio0: "{{ proxmox_datastore }}:{{ talos_cp_disk }}"
      net:
        net0: "virtio,bridge={{ talos_cp_network }},rate=200"
      ide:
        ide1: "{{ proxmox_datastore }}:cloudinit"
        ide2: "local:iso/talos-amd64.iso,media=cdrom"
      boot: "order=ide2;virtio0"
      onboot: true
      state: present
    loop: "{{ range(talos_cp_count | int) }}"
    when: (talos_cp_count | int) > 0
    loop_control:
      label: "talos-cp-{{ item + 1 }}"
    delegate_to: localhost

  - name: "Create {{ talos_worker_count }} Talos Worker VM(s)"
    community.proxmox.proxmox_kvm:
      name: "talos-wrk-{{ item + 1 }}"
      cores: "{{ talos_worker_cores }}"
      cpu: host
      memory: "{{ talos_worker_memory }}"
      ipconfig:
        ipconfig0: "ip={{ network }}.{{ start_octet + (talos_cp_count | int) + item }}/{{ cidr }},gw={{ gateway }}"
      virtio:
        virtio0: "{{ proxmox_datastore }}:{{ talos_worker_disk }}"
      net:
        net0: "virtio,bridge={{ talos_worker_network }},rate=200"
      ide:
        ide1: "{{ proxmox_datastore }}:cloudinit"
        ide2: "local:iso/talos-amd64.iso,media=cdrom"
      boot: "order=ide2;virtio0"
      onboot: true
      state: present
    loop: "{{ range(talos_worker_count | int) }}"
    when: (talos_worker_count | int) > 0
    loop_control:
      label: "talos-wrk-{{ item + 1 }}"
    delegate_to: localhost

  - name: "Ensure Talos Control Plane VMs are running"
    community.proxmox.proxmox_kvm:
      name: "talos-cp-{{ item + 1 }}"
      state: started
    register: start_cp_result
    until: start_cp_result is succeeded
    retries: 10
    delay: 5
    loop: "{{ range(talos_cp_count | int) }}"
    when: (talos_cp_count | int) > 0
    loop_control:
      label: "talos-cp-{{ item + 1 }}"
    delegate_to: localhost

  - name: "Ensure Talos Worker VMs are running"
    community.proxmox.proxmox_kvm:
      name: "talos-wrk-{{ item + 1 }}"
      state: started
    register: start_worker_result
    until: start_worker_result is succeeded
    retries: 10
    delay: 5
    loop: "{{ range(talos_worker_count | int) }}"
    when: (talos_worker_count | int) > 0
    loop_control:
      label: "talos-wrk-{{ item + 1 }}"
    delegate_to: localhost

  - name: "Stop Talos Worker VMs (destroy)"
    community.proxmox.proxmox_kvm:
      name: "talos-wrk-{{ item + 1 }}"
      state: stopped
      force: true
    register: stop_worker_result
    until: stop_worker_result is succeeded
    retries: 10
    delay: 5
    loop: "{{ range(talos_worker_count | int) }}"
    when: (talos_worker_count | int) > 0
    loop_control:
      label: "talos-wrk-{{ item + 1 }}"
    delegate_to: localhost
    tags: [destroy, never]

  - name: "Stop Talos Control Plane VMs (destroy)"
    community.proxmox.proxmox_kvm:
      name: "talos-cp-{{ item + 1 }}"
      state: stopped
      force: true
    register: stop_cp_result
    until: stop_cp_result is succeeded
    retries: 10
    delay: 5
    loop: "{{ range(talos_cp_count | int) }}"
    when: (talos_cp_count | int) > 0
    loop_control:
      label: "talos-cp-{{ item + 1 }}"
    delegate_to: localhost
    tags: [destroy, never]

  - name: "Delete Talos Worker VMs (destroy)"
    community.proxmox.proxmox_kvm:
      name: "talos-wrk-{{ item + 1 }}"
      state: absent
    loop: "{{ range(talos_worker_count | int) }}"
    when: (talos_worker_count | int) > 0
    loop_control:
      label: "talos-wrk-{{ item + 1 }}"
    delegate_to: localhost
    tags: [destroy, never]

  - name: "Delete Talos Control Plane VMs (destroy)"
    community.proxmox.proxmox_kvm:
      name: "talos-cp-{{ item + 1 }}"
      state: absent
    loop: "{{ range(talos_cp_count | int) }}"
    when: (talos_cp_count | int) > 0
    loop_control:
      label: "talos-cp-{{ item + 1 }}"
    delegate_to: localhost
    tags: [destroy, never]